FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

# Install CUPS
RUN install_packages \
    avahi \
    bash

# Move setup script and CUPS config to filesystem
COPY ./entry.sh ./entry.sh
COPY ./avahi-daemon.conf /etc/avahi/avahi-daemon.conf

# Start app
CMD ["bash", "entry.sh"]
