FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

# Install CUPS
RUN install_packages \
    avahi \
    bash \
    dbus

# Move setup script and CUPS config to filesystem
COPY ./entry.sh ./entry.sh

# Start app
CMD ["bash", "entry.sh"]
