FROM resin/%%RESIN_MACHINE_NAME%%-debian

# Install other apt deps
RUN apt-get update && apt-get install -y \
  cups \
  hplip \
  smbclient \
  xprintidle \
  avahi-daemon \
  avahi-discover \
  iptables \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Move to app dir
WORKDIR /usr/src/app

# Move app to filesystem
COPY ./app ./

# Uncomment if you want systemd
ENV INITSYSTEM on

# Start app
CMD ["bash", "/usr/src/app/setup.sh"]